name: Daily Warren Buffett Stock Analysis

on:
  schedule:
    # Run at 10:30 UTC (4:00 PM IST) every weekday (Monday-Friday)
    - cron: '30 10 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance numpy tqdm lxml html5lib beautifulsoup4

      - name: Clean old data
        run: |
          mkdir -p data
          rm -f data/stock_data_*.json
          rm -f data/latest.json
          rm -f data/summary_*.json
          echo "Cleaned old data files"

      - name: Clean output directory
        run: |
          mkdir -p output
          rm -rf output/*
          echo "Cleaned output directory"

      - name: Run data collection
        run: python data_collector.py --max-runtime 1.5
        timeout-minutes: 100

      - name: Run Buffett analysis
        run: |
          python buffet_analyzer.py
          echo "Analysis complete - output generated"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true
          full_commit_message: "Update stock analysis for $(date '+%Y-%m-%d')"
      
      - name: Commit latest data file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/latest.json
          git add output/
          git commit -m "Update stock data for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
